# Generated by Django 6.0.4 on 2026-05-11 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_chato_respostachato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='descricao',
        ),
        migrations.AddField(
            model_name='grupo',
            name='estilo',
            field=models.CharField(choices=[('Casual', 'Casual (Só por diversão)'), ('Competitivo', 'Competitivo (Tryhard/Ranked)'), ('Campanha', 'Foco em Missões / Campanha'), ('Iniciantes', 'Aceita Iniciantes (Mentoria)')], default='Casual', max_length=50),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='genero',
            field=models.CharField(choices=[('Ação', 'Ação e Aventura'), ('Arcade', 'Arcade / Luta'), ('RPG', 'RPG / MMORPG'), ('FPS', 'Tiro em Primeira Pessoa (FPS)'), ('Esportes', 'Esportes / Corrida'), ('Estratégia', 'Estratégia / MOBA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='plataforma',
            field=models.CharField(choices=[('PC', 'PC (Windows/Steam)'), ('PS5', 'PlayStation 5'), ('PS4', 'PlayStation 4'), ('Xbox Series', 'Xbox Series X/S'), ('Xbox One', 'Xbox One'), ('Switch', 'Nintendo Switch'), ('Mobile', 'Smartphone / Mobile')], max_length=50),
        ),
        migrations.CreateModel(
            name='MensagemGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='lobby.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
