# Generated by Django 6.0.4 on 2026-05-19 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_remove_grupo_descricao_grupo_estilo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='grupos_que_participo', to=settings.AUTH_USER_MODEL),
        ),
    ]
