# Generated by Django 6.0.4 on 2026-06-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_grupo_membros'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='descricao',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='jogo',
            name='capa_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
