# Generated by Django 6.0.4 on 2026-06-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0008_grupo_descricao_jogo_capa_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
    ]
